index:
    path: /
    controller: App\Controller\Index::index

boxes:
    path: /boxes
    controller: App\Controller\Boxes::index

madeByYourOwn:
    path: /madeByYourOwn
    controller: App\Controller\MadeByYourOwn::index

orderBox:
    path: /orderBox/{idBox}
    controller: App\Controller\OrderBox::index
    requirements:
        idBox: '\d+'

enter:
    path: /enter
    controller: App\Controller\Enter::index

registration:
    path: /registration
    controller: App\Controller\Registration::index

