index:
    path: /
    controller: App\Controller\Index::index

boxes:
    path: /boxes
    controller: App\Controller\Boxes::index

madeByYourOwn:
    path: /madeByYourOwn
    controller: App\Controller\MadeByYourOwn::index
