index:
    path: /
    controller: App\Controller\Index::index

boxes:
    path: /boxes
    controller: App\Controller\Boxes::index

madeByYourOwn:
    path: /madeByYourOwn
    controller: App\Controller\MadeByYourOwn::index

orderBox:
    path: /orderBox/{idBox}
    controller: App\Controller\OrderBox::index
    requirements:
        idBox: '\d+'

enter:
    path: /enter
    methods: GET
    controller: App\Controller\Enter::index

authUser:
    path: /enter
    methods: POST
    controller: App\Controller\Enter::authUser

logout:
    path: /logout
    controller: App\Controller\Enter::logout

registration:
    path: /registration
    methods: GET
    controller: App\Controller\Registration::index

create_user:
    path: /registration
    methods: POST
    controller: App\Controller\Registration::createUser

